Repository ctc-oss/omega-edit, pull requests merged in 2022-09, with the labels that each got.

#371 implement the frequecy profiler in scala
  build.sh
  src/rpc/client/ts/src/session.ts
  src/rpc/client/ts/tests/specs/profiler.spec.ts
  src/rpc/client/ts/tests/specs/stressTest.spec.ts
  src/rpc/protos/omega_edit.proto
  src/rpc/server/scala/api/src/main/scala/com/ctc/omega_edit/FFI.scala
  src/rpc/server/scala/api/src/main/scala/com/ctc/omega_edit/SessionImpl.scala
  src/rpc/server/scala/api/src/main/scala/com/ctc/omega_edit/api/Session.scala
  src/rpc/server/scala/api/src/test/scala/com/ctc/omega_edit/SessionImplSpec.scala
  src/rpc/server/scala/serv/src/main/scala/com/ctc/omega_edit/grpc/EditorService.scala
  src/rpc/server/scala/serv/src/main/scala/com/ctc/omega_edit/grpc/Session.scala
  src/rpc/server/scala/serv/src/test/scala/com/ctc/omega_edit/grpc/ExampleSpec.scala
Labels: grpc, server, scala

#372 Merge CI tests into one file/job
  .github/workflows/scala-steward.yml
  .github/workflows/scala.yml
  .github/workflows/tests.yml
  .github/workflows/unit-tests.yml
  .gitignore
Labels: enhancement, CI

#374 enable Windows integration test
  .github/workflows/tests.yml
Labels: testing, CI, cross-platform

#376 lint fixes
  src/include/omega_edit/stl_string_adaptor.hpp
  src/lib/edit.cpp
  src/lib/encode.c
  src/lib/impl_/find.cpp
  src/lib/stl_string_adapter.cpp
  src/lib/utility.c
Labels: code quality, C, C++

#377 Add client TypeScript tests to CI
  .github/workflows/tests.yml
Labels: testing, CI

#378 typescript lint fixes
  src/rpc/client/ts/tests/specs/common.ts
  src/rpc/client/ts/tests/specs/editing.spec.ts
  src/rpc/client/ts/tests/specs/profiler.spec.ts
  src/rpc/client/ts/tests/specs/search.spec.ts
  src/rpc/client/ts/tests/specs/stressTest.spec.ts
  src/rpc/client/ts/tests/specs/undoRedo.spec.ts
  src/rpc/client/ts/tests/specs/version.spec.ts
  src/rpc/client/ts/tests/specs/viewport.spec.ts
Labels: code quality, javascript

#380 add search warnings
  src/include/omega_edit/search.h
  src/include/omega_edit/stl_string_adaptor.hpp
Labels: code quality, C, C++

#383 Disable generation of default values from protobuf.
  src/rpc/server/scala/serv/src/main/protobuf/package.proto
  src/rpc/server/scala/serv/src/main/scala/com/ctc/omega_edit/grpc/EditorService.scala
  src/rpc/server/scala/serv/src/test/scala/com/ctc/omega_edit/grpc/ExampleSpec.scala
Labels: code quality, scala

#393 cmake no longer generates gRPC TypeScript code
  CMakeLists.txt
Labels: client, javascript, build

#394 upgrade grpc
  CMakeLists.txt
Labels: grpc, server, C++

#398 fix scala lints
  src/rpc/server/scala/api/src/test/scala/com/ctc/omega_edit/SessionImplSpec.scala
  src/rpc/server/scala/api/src/test/scala/com/ctc/omega_edit/support/SessionSupport.scala
  src/rpc/server/scala/build.sbt
  src/rpc/server/scala/project/BuildSupport.scala
  src/rpc/server/scala/serv/src/main/scala/com/ctc/omega_edit/grpc/EditorService.scala
  src/rpc/server/scala/serv/src/test/scala/com/ctc/omega_edit/grpc/ExampleSpec.scala
Labels: code quality, scala

#399 upgrade npm
  src/rpc/client/ts/package.json
Labels: javascript, dependencies

#381 Link all subprojects to root project.
  src/rpc/server/scala/build.sbt
Labels: enhancement, build

#400 document TypeScript client public API
  src/include/omega_edit/edit.h
  src/include/omega_edit/search.h
  src/include/omega_edit/session.h
  src/rpc/client/ts/.gitignore
  src/rpc/client/ts/.prettierignore
  src/rpc/client/ts/package-lock.json
  src/rpc/client/ts/package.json
  src/rpc/client/ts/src/change.ts
  src/rpc/client/ts/src/session.ts
  src/rpc/client/ts/src/settings.ts
  src/rpc/client/ts/src/version.ts
  src/rpc/client/ts/src/viewport.ts
  src/rpc/client/ts/tsconfig.json
  src/rpc/client/ts/typedoc.json
  src/rpc/server/scala/project/Rat.scala
Labels: documentation, client, javascript

#401 allow RPC server interface to be configurable
  src/rpc/client/ts/.gitignore
  src/rpc/client/ts/runTests.ts
  src/rpc/server/scala/serv/src/main/scala/com/ctc/omega_edit/grpc/EditorService.scala
  src/rpc/server/scala/serv/src/main/scala/com/ctc/omega_edit/grpc/boot.scala
Labels: enhancement, grpc, server, scala
