Repository ctc-oss/omega-edit, pull requests merged in 2022-02, with the labels that each got.

#157 readme section on versioning
  README.md
Labels: documentation

#158 fix simple_c.c and simple.cpp viewport callback lint
  src/examples/simple.cpp
  src/examples/simple_c.c
Labels: code quality

#164 reorganize the rpc directory for adding in different implementations
  src/rpc/CMakeLists.txt
  src/rpc/server/cpp/server.cpp
  src/rpc/server/cpp/server_cbk.cpp
  src/rpc/server/cpp/worker_queue/worker_queue.cpp
  src/rpc/server/cpp/worker_queue/worker_queue.hpp
  src/rpc/tests/server_test.cpp
Labels: grpc

#166 generate js client in src/rpc/client/js
  src/rpc/CMakeLists.txt
Labels: grpc, client, javascript

#165 Build a shared library
  CMakeLists.txt
Labels: bindings

#176 flatten ChangeDetailsResponse rpc message
  src/rpc/protos/omega_edit.proto
  src/rpc/server/cpp/server.cpp
  src/rpc/tests/server_test.cpp
Labels: grpc

#182 server_test controls a server process
  src/rpc/tests/server_test.cpp
Labels: testing

#187 floating viewports
  src/examples/peek.cpp
  src/examples/rotate.cpp
  src/examples/simple.cpp
  src/examples/simple_c.c
  src/include/omega_edit/edit.h
  src/include/omega_edit/fwd_defs.h
  src/include/omega_edit/viewport.h
  src/lib/edit.cpp
  src/lib/impl_/data_def.hpp
  src/lib/impl_/data_segment_def.hpp
  src/lib/impl_/internal_fun.cpp
  src/lib/viewport.cpp
  src/lib/visit.cpp
  src/rpc/protos/omega_edit.proto
  src/rpc/server/cpp/server.cpp
  src/rpc/tests/server_test.cpp
  src/tests/omega_test.cpp
  src/tests/play.cpp
  src/tests/replay.cpp
Labels: enhancement

#188 add server as server_test dependency
  src/rpc/CMakeLists.txt
  src/rpc/server/cpp/server.cpp
  src/tests/omega_test.cpp
Labels: build

#189 add rpc services to get last change and last undo
  src/include/omega_edit/session.h
  src/rpc/protos/omega_edit.proto
  src/rpc/server/cpp/server.cpp
  src/rpc/tests/server_test.cpp
Labels: grpc

#191 replace cwalk with boost::filesystem
  CMakeLists.txt
  cmake/FindLibUUID.cmake
  src/include/omega_edit/utility.h
  src/lib/edit.cpp
  src/lib/filesystem.cpp
  src/lib/utility.c
  src/tests/omega_test.cpp
Labels: code quality

#195 get computed file size rpc
  src/rpc/protos/omega_edit.proto
  src/rpc/server/cpp/server.cpp
  src/rpc/tests/server_test.cpp
Labels: grpc

#196 Change osx platform string
  src/bindings/scala/README.md
  src/bindings/scala/project/BuildSupport.scala
Labels: bindings, scala

#198 util functions to compute filesize and replace unlink
  src/include/omega_edit/utility.h
  src/lib/edit.cpp
  src/lib/filesystem.cpp
  src/lib/impl_/internal_fun.cpp
  src/lib/session.cpp
  src/lib/utility.c
  src/tests/omega_test.cpp
Labels: cross-platform

#202 Scala gRPC reference impl
  .github/workflows/scala.yml
  src/bindings/scala/README.md
  src/rpc/server/scala/.scalafmt.conf
  src/rpc/server/scala/README.md
  src/rpc/server/scala/build.sbt
  src/rpc/server/scala/project/BuildSupport.scala
  src/rpc/server/scala/project/build.properties
  src/rpc/server/scala/project/plugins.sbt
  src/rpc/server/scala/src/main/resources/application.conf
  src/rpc/server/scala/src/main/scala/com/ctc/omega_edit/grpc/EditorService.scala
  src/rpc/server/scala/src/main/scala/com/ctc/omega_edit/grpc/Editors.scala
  src/rpc/server/scala/src/main/scala/com/ctc/omega_edit/grpc/Session.scala
  src/rpc/server/scala/src/main/scala/com/ctc/omega_edit/grpc/Viewport.scala
  src/rpc/server/scala/src/main/scala/com/ctc/omega_edit/grpc/boot.scala
  src/rpc/server/scala/src/test/scala/com/ctc/omega_edit/grpc/ExampleSpec.scala
Labels: grpc, scala

#207 deploy documentation CI
  .github/workflows/deploy-docs.yml
Labels: documentation, CI

#209 get lgtm working again
  .github/workflows/deploy-docs.yml
  .github/workflows/unit-tests.yml
  .lgtm.yml
  build.sh
  src/tests/CMakeLists.txt
  src/tests/integration/omega_test.cpp
Labels: CI
