Repository ctc-oss/omega-edit, pull requests merged in 2022-12, with the labels that each got.

#466 Add support for aarch, eg mac m1
  src/rpc/server/scala/project/BuildSupport.scala
Labels: cross-platform

#467 Upgrade catch2 from 3.1.0 to 3.2.0
  CMakeLists.txt
Labels: dependencies

#474 Multiple updates
  .github/release.sbt
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/release.yml
  .github/workflows/scala-steward.yml
  .github/workflows/tests.yml
  CMakeLists.txt
  src/rpc/client/ts/package-lock.json
  src/rpc/client/ts/package.json
  src/rpc/server/scala/build.sbt
  src/rpc/server/scala/project/BuildSupport.scala
Labels: CI
