Repository ctc-oss/omega-edit, pull requests merged in 2022-03, with the labels that each got.

#217 cpack support
  .github/workflows/unit-tests.yml
  .gitignore
  build.sh
  packaging/.cpack_ignore
  packaging/CMakeLists.txt
  project/Rat.scala
Labels: build, packaging

#219 doc workflow update
  .github/workflows/deploy-docs.yml
Labels: documentation, CI, publication

#214 grpc version bump
  .github/workflows/unit-tests.yml
  build.sh
  src/rpc/CMakeLists.txt
  src/rpc/server/cpp/server.cpp
  src/rpc/tests/server_test.cpp
Labels: grpc

#228 scala: Check file exists on session create
  src/bindings/scala/api/src/main/scala/com/ctc/omega_edit/ChangeImpl.scala
  src/bindings/scala/api/src/main/scala/com/ctc/omega_edit/SessionImpl.scala
  src/bindings/scala/api/src/main/scala/com/ctc/omega_edit/ViewportImpl.scala
  src/bindings/scala/api/src/main/scala/com/ctc/omega_edit/api/OmegaEdit.scala
  src/bindings/scala/api/src/test/scala/com/ctc/omega_edit/SessionImplSpec.scala
  src/rpc/server/scala/src/main/scala/com/ctc/omega_edit/grpc/Editors.scala
  src/rpc/server/scala/src/main/scala/com/ctc/omega_edit/grpc/Session.scala
  src/rpc/server/scala/src/test/scala/com/ctc/omega_edit/grpc/ExampleSpec.scala
Labels: grpc, scala

#233 add more viewports to RPC server_test
  build.sh
  src/rpc/tests/server_test.cpp
Labels: testing

#234 build rpc for windows and linux
  .devcontainer/Dockerfile
  .github/workflows/release.yml
  .github/workflows/scala.yml
  .github/workflows/unit-tests.yml
  .vscode/settings.json
  CMakeLists.txt
  build.sh
  docker/Dockerfile.ubuntu20-cpp-env
  src/examples/CMakeLists.txt
  src/examples/play.cpp
  src/lib/edit.cpp
  src/lib/filesystem.cpp
  src/lib/impl_/internal_fun.cpp
  src/lib/search.cpp
  src/lib/session.cpp
  src/lib/utility.c
  src/rpc/CMakeLists.txt
  src/rpc/server/cpp/server.cpp
  src/rpc/server/cpp/worker_queue/worker_queue.cpp
  src/rpc/tests/server_test.cpp
  src/tests/integration/CMakeLists.txt
  src/tests/integration/omega_test.cpp
Labels: testing, CI, cross-platform, server, build

#240 add Scala build and test to build.sh
  build.sh
Labels: build

#241 handle save overwriting file being edited
  CMakeLists.txt
  src/include/omega_edit/edit.h
  src/include/omega_edit/filesystem.h
  src/lib/edit.cpp
  src/lib/filesystem.cpp
  src/rpc/client/ts/package.json
  src/tests/integration/data/session_save.expected.1.dat
  src/tests/integration/data/session_save.expected.2.dat
  src/tests/integration/omega_test.cpp
Labels: C, C++

#244 implement error handling in the C++ RPC server
  src/rpc/server/cpp/server.cpp
Labels: grpc, C++

#229 add dark/light mode toggle to docs
  .github/workflows/deploy-docs.yml
  sphinx/conf.py
Labels: documentation

#248 rpc getOmegaVersion => getVersion
  src/rpc/protos/omega_edit.proto
  src/rpc/server/cpp/server.cpp
  src/rpc/server/scala/src/main/scala/com/ctc/omega_edit/grpc/EditorService.scala
  src/rpc/server/scala/src/test/scala/com/ctc/omega_edit/grpc/ExampleSpec.scala
  src/rpc/tests/server_test.cpp
Labels: grpc

#247 spawn server in windows for server_test
  .github/workflows/unit-tests.yml
  README.md
  src/include/omega_edit/config.h
  src/lib/impl_/macros.h
  src/rpc/protos/omega_edit.proto
  src/rpc/server/cpp/server.cpp
  src/rpc/server/cpp/worker_queue/worker_queue.cpp
  src/rpc/server/cpp/worker_queue/worker_queue.hpp
  src/rpc/server/scala/src/test/scala/com/ctc/omega_edit/grpc/ExampleSpec.scala
  src/rpc/tests/server_test.cpp
  src/tests/integration/omega_test.cpp
Labels: testing, cross-platform, C++

#245 add counter rpc and C++ RPC server implementation
  src/bindings/scala/api/src/main/scala/com/ctc/omega_edit/FFI.scala
  src/bindings/scala/api/src/main/scala/com/ctc/omega_edit/SessionImpl.scala
  src/bindings/scala/api/src/main/scala/com/ctc/omega_edit/api/Session.scala
  src/include/omega_edit/session.h
  src/lib/session.cpp
  src/rpc/protos/omega_edit.proto
  src/rpc/server/cpp/server.cpp
  src/rpc/server/scala/src/main/scala/com/ctc/omega_edit/grpc/EditorService.scala
  src/rpc/server/scala/src/main/scala/com/ctc/omega_edit/grpc/Editors.scala
  src/rpc/server/scala/src/main/scala/com/ctc/omega_edit/grpc/Session.scala
  src/rpc/server/scala/src/test/scala/com/ctc/omega_edit/grpc/ExampleSpec.scala
  src/rpc/tests/server_test.cpp
  src/tests/integration/omega_test.cpp
Labels: testing, grpc, scala, C++
