Repository ctc-oss/omega-edit, pull requests merged in 2022-05, with the labels that each got.

#262 Fix omega-edit-native for windows
  .github/workflows/release.yml
  CMakeLists.txt
  src/rpc/client/ts/package.json
Labels: bug, cross-platform

#264 initial client testing groundwork
  project/Rat.scala
  src/lib/impl_/internal_fun.cpp
  src/lib/search.cpp
  src/lib/segment.cpp
  src/lib/visit.cpp
  src/rpc/client/ts/package-lock.json
  src/rpc/client/ts/package.json
  src/rpc/client/ts/src/change.ts
  src/rpc/client/ts/src/session.ts
  src/rpc/client/ts/src/settings.ts
  src/rpc/client/ts/src/version.ts
  src/rpc/client/ts/src/viewport.ts
  src/rpc/client/ts/tests/package-lock.json
  src/rpc/client/ts/tests/package.json
  src/rpc/client/ts/tests/specs/client.spec.ts
  src/rpc/client/ts/tests/tsconfig.json
  src/rpc/protos/omega_edit.proto
  src/rpc/server/cpp/server.cpp
  src/rpc/server/scala/build.sbt
Labels: testing

#268 C++17 filesystem linker fix for older GNU C++ compilers
  CMakeLists.txt
  src/rpc/CMakeLists.txt
Labels: cross-platform, C++, build

#269 Fix for daffodil-vscode
  CMakeLists.txt
  src/rpc/client/ts/package.json
  src/rpc/server/scala/build.sbt
Labels: scala
