Repository ctc-oss/omega-edit, pull requests merged in 2023-08, with the labels that each got.

#716 add JVM version to heartbeat info
  packages/client/src/server.ts
  proto/omega_edit.proto
  server/scala/api/src/main/scala/com/ctc/omega_edit/api/OmegaEdit.scala
  server/scala/api/src/main/scala/com/ctc/omega_edit/api/Version.scala
  server/scala/project/BuildSupport.scala
  server/scala/serv/src/main/scala/com/ctc/omega_edit/grpc/EditorService.scala
Labels: grpc, server, scala

#717 include the JVM path in the heartbeat
  packages/client/src/server.ts
  packages/client/src/version.ts
  packages/client/tests/specs/session.spec.ts
  packages/client/tests/specs/version.spec.ts
  proto/omega_edit.proto
  server/scala/serv/src/main/scala/com/ctc/omega_edit/grpc/EditorService.scala
  server/scala/serv/src/test/scala/com/ctc/omega_edit/grpc/ExampleSpec.scala
Labels: grpc, server, scala, javascript

#727 upgrade prettier
  package.json
  yarn.lock
Labels: javascript, dependencies

#724 profile DOS EOL
  core/src/examples/simple_c.c
  core/src/examples/transform.c
  core/src/include/omega_edit/session.h
  core/src/lib/check.cpp
  core/src/lib/edit.cpp
  core/src/lib/session.cpp
  core/src/lib/version.c
  core/src/tests/omega_test.cpp
  packages/client/src/session.ts
  packages/client/tests/specs/profiler.spec.ts
  packages/client/tests/specs/session.spec.ts
  server/scala/api/src/main/scala/com/ctc/omega_edit/SessionImpl.scala
  server/scala/serv/src/test/scala/com/ctc/omega_edit/grpc/ExampleSpec.scala
Labels: enhancement

#740 Fix building locally
  .gitignore
  server/scala/build.sbt
  server/scala/project/BuildSupport.scala
Labels: bug
