Repository ctc-oss/omega-edit, pull requests merged in 2023-05, with the labels that each got.

#643 add IO flags to save session
  core/src/examples/play.cpp
  core/src/examples/profile.c
  core/src/examples/replace.cpp
  core/src/examples/replay.cpp
  core/src/examples/rotate.cpp
  core/src/examples/simple.cpp
  core/src/examples/simple_c.c
  core/src/examples/slice.cpp
  core/src/examples/transform.c
  core/src/include/omega_edit/change.h
  core/src/include/omega_edit/config.h
  core/src/include/omega_edit/edit.h
  core/src/include/omega_edit/encode.h
  core/src/include/omega_edit/export.h
  core/src/include/omega_edit/filesystem.h
  core/src/include/omega_edit/fwd_defs.h
  core/src/include/omega_edit/search.h
  core/src/include/omega_edit/segment.h
  core/src/include/omega_edit/session.h
  core/src/include/omega_edit/utility.h
  core/src/include/omega_edit/viewport.h
  core/src/lib/edit.cpp
  core/src/lib/filesystem.cpp
  core/src/lib/impl_/find.cpp
  core/src/lib/impl_/find.h
  core/src/lib/impl_/internal_fun.cpp
  core/src/lib/impl_/internal_fun.hpp
  core/src/lib/impl_/macros.h
  core/src/lib/search.cpp
  core/src/lib/session.cpp
  core/src/lib/stl_string_adapter.cpp
  core/src/lib/utility.c
  core/src/lib/version.c
  core/src/lib/viewport.cpp
  core/src/lib/visit.cpp
  core/src/tests/data/search-test.dat
  core/src/tests/data/search-test.expected.1.dat
  core/src/tests/omega_test.cpp
  packages/client/package.json
  packages/client/src/session.ts
  packages/client/tests/specs/search.spec.ts
  packages/client/tests/specs/session.spec.ts
  packages/client/tests/specs/undoRedo.spec.ts
  proto/omega_edit.proto
  server/scala/api/src/main/scala/com/ctc/omega_edit/FFI.scala
  server/scala/api/src/main/scala/com/ctc/omega_edit/SessionImpl.scala
  server/scala/api/src/main/scala/com/ctc/omega_edit/api/IOFlags.scala
  server/scala/api/src/main/scala/com/ctc/omega_edit/api/Session.scala
  server/scala/api/src/main/scala/com/ctc/omega_edit/api/SessionEvent.scala
  server/scala/api/src/main/scala/com/ctc/omega_edit/api/ViewportEvent.scala
  server/scala/api/src/test/scala/com/ctc/omega_edit/SessionImplSpec.scala
  server/scala/serv/src/main/scala/com/ctc/omega_edit/grpc/EditorService.scala
  server/scala/serv/src/main/scala/com/ctc/omega_edit/grpc/Session.scala
  server/scala/serv/src/test/scala/com/ctc/omega_edit/grpc/ExampleSpec.scala
  yarn.lock
Labels: enhancement, grpc, client, server, scala, javascript, C

#653 save session no longer resets session when original file overwritten
  core/src/lib/edit.cpp
  core/src/tests/omega_test.cpp
Labels: C

#651 Include file size in session creation response if a file name was given
  packages/client/tests/specs/session.spec.ts
  proto/omega_edit.proto
  server/scala/serv/src/main/scala/com/ctc/omega_edit/grpc/EditorService.scala
  server/scala/serv/src/main/scala/com/ctc/omega_edit/grpc/Editors.scala
  server/scala/serv/src/main/scala/com/ctc/omega_edit/grpc/Session.scala
Labels: enhancement, grpc, client, server, scala, javascript

#652 build on older OS versions to support older OS versions
  .github/workflows/deploy-docs.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
Labels: CI, cross-platform, build

#655 Rework release workflow
  .github/workflows/release.yml
  .github/workflows/tests.yml
Labels: CI

#654 touch checkpoint on original file overwrite
  core/CMakeLists.txt
  core/src/lib/edit.cpp
  core/src/lib/filesystem.cpp
  core/src/tests/omega_test.cpp
  package.json
  packages/client/package.json
  packages/client/tests/specs/session.spec.ts
  packages/server/package.json
Labels: bug, C

#659 add Count lines of code (CLOC) to CI
  .github/workflows/release.yml
Labels: documentation, build

#660 add missing comments for a few client functions
  packages/client/src/session.ts
  packages/client/src/viewport.ts
Labels: documentation, client

#662 Fix linux amd64 jar missing lib file.
  .github/workflows/release.yml
Labels: CI

#667 Use single jar for native
  .github/workflows/release.yml
  server/scala/api/src/main/scala/com/ctc/omega_edit/FFI.scala
  server/scala/build.sbt
  server/scala/project/BuildSupport.scala
  server/scala/spi/src/main/scala-2.12/com/ctc/omega_edit/spi/PlatformInfoLoader.scala
  server/scala/spi/src/main/scala-2.13/com/ctc/omega_edit/spi/PlatformInfoLoader.scala
  server/scala/spi/src/main/scala/com/ctc/omega_edit/spi/NativeBuildInfo.scala
Labels: cross-platform, server, scala
