Repository ctc-oss/omega-edit, pull requests merged in 2024-02, with the labels that each got.

#879 upgrade Catch2
  core/CMakeLists.txt
  core/cmake/features.h.in
Labels: testing, C, C++, dependencies

#878 Add CI support for macos and linux arm64
  .github/workflows/build-middleware-docker/action.yml
  .github/workflows/build-middleware/action.yml
  .github/workflows/build-native-docker/action.yml
  .github/workflows/build-native/action.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .gitignore
  docker/Dockerfile.ubuntu20-cpp-env
Labels: cross-platform, build

#840 Bit handling in the native Ωedit library
  core/CMakeLists.txt
  core/src/examples/replace.cpp
  core/src/include/omega_edit/encode.h
  core/src/include/omega_edit/utility.h
  core/src/lib/edit.cpp
  core/src/lib/impl_/data_def.hpp
  core/src/lib/impl_/find.cpp
  core/src/lib/impl_/find.h
  core/src/lib/session.cpp
  core/src/lib/utility.c
  core/src/lib/viewport.cpp
  core/src/tests/generate_file.cpp
  core/src/tests/omega_test.cpp
  core/src/tests/test_util.hpp
Labels: enhancement, C, C++
