Repository ctc-oss/omega-edit, pull requests merged in 2024-10, with the labels that each got.

#1009 Fix copyright date
  server/scala/serv/src/test/scala/com/ctc/omega_edit/grpc/Bug976Spec.scala
Labels: bug, legal

#981 upgrade catch2 to v3.7.0
  core/CMakeLists.txt
  packages/server/src/index.ts
Labels: testing, C, C++, dependencies

#1013 yarn updates and lint fix in server-side index.ts
  packages/server/src/index.ts
  yarn.lock
Labels: code quality, dependencies

#1014 add hints to update-version target in makefile
  Makefile
Labels: documentation
